# Change these first
owner: HaoduStudio
repo: status-page

sites:
  - name: Homepage
    url: https://www.dailynotes.top
  - name: Gitlab
    url: https://git.nexaorion.cn
  - name: Docs
    url: https://police.nexaorion.cn
  - name: Account Gateway
    url: https://passport.nexaorion.cn
  - name: API Gateway
    url: https://admin-passport.nexaorion.cn

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.nexaorion.tech
  # baseUrl: /your-repo-name
  name: Nexaorion Status
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
commitMessages:
  readmeContent: ":pencil: Update summary in README [skip ci] [upptime]"
  summaryJson: ":card_file_box: Update status summary [skip ci] [upptime]"
  statusChange: "$EMOJI $SITE_NAME is $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms) [skip ci] [upptime]"
  graphsUpdate: ":bento: Update graphs [skip ci] [upptime]"
